/**
 * Robusthetskontroll utan JavaScript (opt-in, rådgivande)
 *
 * Mäter hur mycket av sidans innehåll som finns tillgängligt när JavaScript
 * inte körs. En sida som är helt tom utan JS är skör: när skriptet failar
 * (nät, proxy, brandvägg, webbläsartillägg) får användaren inte en försämrad
 * sida, utan en TOM sida.
 *
 * VIKTIGT, LÄS INNAN DU ÄNDRAR NÅGOT HÄR:
 * Detta är INTE ett WCAG-fel och får ALDRIG rapporteras som ett.
 * Det finns inget framgångskriterium i WCAG 2.0, 2.1 eller 2.2 som kräver att
 * en sida fungerar utan JavaScript. Princip 4 "Robust" handlar om att innehåll
 * ska kunna tolkas av user agents och hjälpmedel, inte om progressive
 * enhancement. SC 4.1.2 förutsätter tvärtom skriptgenererade komponenter
 * ("components generated by scripts"). Kravet fanns i WCAG 1.0 checkpoint 6.3
 * (1999) men togs bort i WCAG 2.0. W3C:s egen teknik SCR38 säger uttryckligen:
 * "this is not required for conformance with WCAG 2.x."
 *
 * Därför: resultatet härifrån påverkar aldrig score eller complianceStatus.
 * Det är en separat robusthetsindikator, märkt som rekommendation.
 */

import type { Browser } from 'puppeteer';

/**
 * Under denna täckningsgrad räknas sidan som i praktiken tom utan JS.
 * 5 % fångar sidor vars enda JS-fria innehåll är en cookie-banner, en
 * skiplänk eller ett "aktivera JavaScript"-meddelande. Det är inte innehåll.
 */
export const NOSCRIPT_EMPTY_THRESHOLD = 0.05;

/**
 * Under denna täckningsgrad saknas en väsentlig del av innehållet utan JS.
 * 50 % innebär att merparten av det primära innehållet är klientrenderat.
 * Över tröskeln finns kärninnehållet serverrenderat och JS är en förstärkning,
 * vilket är den robusthet vi vill se.
 */
export const NOSCRIPT_PARTIAL_THRESHOLD = 0.5;

export type NoScriptVerdict = 'ok' | 'partial' | 'empty' | 'unknown';

export interface NoScriptResult {
    /** Antal tecken synlig text när JS inte körts. */
    textLengthWithoutJs: number;
    /** Antal tecken synlig text i den ordinarie (hydrerade) skanningen. */
    textLengthWithJs: number;
    /** textLengthWithoutJs / textLengthWithJs, klampad till 0..1. */
    coverageRatio: number;
    verdict: NoScriptVerdict;
    hasContentWithoutJs: boolean;
    /** Har sidan ett <noscript>-element som fallback? */
    hasNoScriptFallback: boolean;
    /**
     * Permanent false. Finns i datamodellen för att göra garantin explicit och
     * omöjlig att missa för den som konsumerar JSON:en. Se filhuvudet.
     */
    isWcagViolation: false;
    /** Permanent false. Robusthetsfynd får aldrig sänka konformansscoren. */
    affectsScore: false;
    /** Satt endast om mätningen misslyckades. Då är verdict 'unknown'. */
    error?: string;
}

/**
 * Ren funktion: bedömer täckningsgrad utifrån två textlängder.
 * Separerad från webbläsarlogiken så tröskelvärdena kan enhetstestas utan
 * att starta en browser.
 */
export function evaluateNoScriptCoverage(
    textLengthWithoutJs: number,
    textLengthWithJs: number,
    hasNoScriptFallback = false
): NoScriptResult {
    const withoutJs = Math.max(0, Math.trunc(textLengthWithoutJs) || 0);
    const withJs = Math.max(0, Math.trunc(textLengthWithJs) || 0);

    const base: Omit<NoScriptResult, 'coverageRatio' | 'verdict' | 'hasContentWithoutJs'> = {
        textLengthWithoutJs: withoutJs,
        textLengthWithJs: withJs,
        hasNoScriptFallback,
        isWcagViolation: false,
        affectsScore: false
    };

    // Ingen text ens MED JS: sidan är tom, ett fel, eller ren media. Vi kan inte
    // säga något meningsfullt om täckningsgraden och larmar därför inte alls.
    if (withJs === 0) {
        return {
            ...base,
            coverageRatio: 0,
            verdict: 'unknown',
            hasContentWithoutJs: withoutJs > 0
        };
    }

    // Klampas till 1: en JS-fri sida kan innehålla MER text än den hydrerade
    // (t.ex. ett <noscript>-block som JS sedan tar bort). Det är inte >100 %.
    const coverageRatio = Math.min(1, withoutJs / withJs);

    let verdict: NoScriptVerdict;
    if (coverageRatio < NOSCRIPT_EMPTY_THRESHOLD) {
        verdict = 'empty';
    } else if (coverageRatio < NOSCRIPT_PARTIAL_THRESHOLD) {
        verdict = 'partial';
    } else {
        verdict = 'ok';
    }

    return {
        ...base,
        coverageRatio,
        verdict,
        hasContentWithoutJs: coverageRatio >= NOSCRIPT_EMPTY_THRESHOLD
    };
}

export interface NoScriptProbeOptions {
    url: string;
    userAgent?: string;
    viewport?: { width: number; height: number };
    timeout?: number;
}

export interface NoScriptProbeMeasurement {
    /** Synlig text utan JS, EXKLUSIVE innehållet i <noscript>. Se probe-funktionen. */
    textLength: number;
    hasNoScriptFallback: boolean;
}

/**
 * Laddar sidan med JavaScript avstängt och mäter hur mycket text som finns.
 *
 * GOTCHA (uppmätt, gissa inte om detta):
 * Man kan INTE ladda sidan med setJavaScriptEnabled(false) och sedan köra
 * mätningen eller axe med JS fortfarande avstängt. Flaggan sätter CDP:s
 * Emulation.setScriptExecutionDisabled, vilket dödar timers och
 * microtask-pumpning. Allt asynkront (t.ex. axe.run) hänger då för evigt och
 * Puppeteer kastar "Runtime.callFunctionOn timed out".
 *
 * Lösningen: stäng av JS UNDER laddningen, slå PÅ det igen INNAN vi mäter.
 * Sidans egna skript hoppades över under parsningen och återexekveras inte när
 * JS slås på igen, så DOM:en förblir fryst i sitt JS-fria tillstånd samtidigt
 * som vi får tillbaka en fungerande exekveringsmiljö att mäta med.
 */
export async function probeWithoutJavaScript(
    browser: Browser,
    options: NoScriptProbeOptions
): Promise<NoScriptProbeMeasurement> {
    const page = await browser.newPage();

    try {
        if (options.userAgent) await page.setUserAgent(options.userAgent);
        if (options.viewport) await page.setViewport(options.viewport);

        // 1. JS av: sidans skript hoppas över under parsningen.
        await page.setJavaScriptEnabled(false);

        await page.goto(options.url, {
            waitUntil: 'domcontentloaded',
            timeout: options.timeout ?? 60000
        });

        // 2. JS på igen: DOM:en är redan fryst i sitt JS-fria läge. Se gotchan ovan.
        await page.setJavaScriptEnabled(true);

        // 3. Mät. Ingen hydration-wait här, det är hela poängen.
        //
        // <noscript>-innehållet RÄKNAS BORT. Det är inte en detalj, det är
        // skillnaden mellan ett sant och ett falskt mätvärde:
        // ett <noscript>-block renderas bara när JS är av, aldrig när JS är på.
        // Räknar vi med det jämför vi text som finns i den ena mätningen men är
        // omöjlig i den andra, och täckningsgraden blåses upp. Uppmätt på
        // excalidraw.com: meddelandet "You need to enable JavaScript" gav 16 %
        // "täckning" på en sida som i verkligheten har noll innehåll utan JS.
        //
        // Vi kan dölja elementen med style i stället för att räkna av deras
        // textlängd, eftersom JS är påslaget igen: innerText respekterar
        // display:none, så vi får rätt siffra direkt från layouten.
        return await page.evaluate(() => {
            const noScriptEls = Array.from(document.querySelectorAll('noscript'));
            noScriptEls.forEach(el => {
                (el as HTMLElement).style.display = 'none';
            });

            return {
                textLength: (document.body?.innerText ?? '').trim().length,
                hasNoScriptFallback: noScriptEls.length > 0
            };
        });
    } finally {
        await page.close();
    }
}
